title = "Cheuk çš„éƒ¨è½æ ¼ :p"
baseURL = 'https://cheuk-blog.github.io/'
languageCode = 'zh-tw'
theme = "hugo-theme-stack"
cleanDestinationDir = true

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

# Redirect
# in layouts/index.html

# Side-wide settings
[params]
  mainsections = ["post"]
  favicon = "/favicon.ico"
  custom_CSS = ["css/custom.css"]

# Custom Menu
[menu]
  [[menu.main]]
      name = "é¦–é "
      url = "/home"
      weight = 10
      identifier = "home"
      [menu.main.params]
          icon = "chevron-right"
          newTab = false
  [[menu.main]]
      name = "æ–‡ç« "
      url = "/posts"
      weight = 20
      identifier = "posts"
      [menu.main.params]
          icon = "chevron-right"
          newTab = false
  [[menu.main]]
      name = "åšç·Šå’©"
      url = "/now"
      weight = 30
      identifier = "now"
      [menu.main.params]
          icon = "chevron-right"
          newTab = false
  [[menu.main]]
      name = "é—œæ–¼"
      url = "/about"
      weight = 40
      identifier = "about"
      [menu.main.params]
          icon = "chevron-right"
          newTab = false

  [[menu.social]]
  name = "rss"
  url = "https://cheuk-blog.github.io/posts/index.xml"
  weight = 50
  [menu.social.params]
    icon = "rss"
    newTab = true

# Sidebar
[params.sidebar]
  emoji = "ğŸš‚"
  subtitle = "å™—å“ˆå“ˆï¼ˆãƒ‘ãƒ’ãƒ£ãƒ’ãƒ£ãƒƒï¼ï¼‰"
  avatar.enabled = true
  avatar.src = "images/avatar.png"

# Article
[params.article]
  readingtime = false
